//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.07.24 at 11:55:17 PM CEST 
//


package org.oasis_open.docs.ns.bpel4people.ws_humantask.context._200803;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.oasis_open.docs.ns.bpel4people.ws_humantask.context._200803 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _TaskInitiator_QNAME = new QName("http://docs.oasis-open.org/ns/bpel4people/ws-humantask/context/200803", "taskInitiator");
    private final static QName _Recipients_QNAME = new QName("http://docs.oasis-open.org/ns/bpel4people/ws-humantask/context/200803", "recipients");
    private final static QName _PotentialOwners_QNAME = new QName("http://docs.oasis-open.org/ns/bpel4people/ws-humantask/context/200803", "potentialOwners");
    private final static QName _GenericHumanRole_QNAME = new QName("http://docs.oasis-open.org/ns/bpel4people/ws-humantask/context/200803", "genericHumanRole");
    private final static QName _HumanTaskResponseContext_QNAME = new QName("http://docs.oasis-open.org/ns/bpel4people/ws-humantask/context/200803", "humanTaskResponseContext");
    private final static QName _TaskStakeholders_QNAME = new QName("http://docs.oasis-open.org/ns/bpel4people/ws-humantask/context/200803", "taskStakeholders");
    private final static QName _ExcludedOwners_QNAME = new QName("http://docs.oasis-open.org/ns/bpel4people/ws-humantask/context/200803", "excludedOwners");
    private final static QName _HumanTaskRequestContext_QNAME = new QName("http://docs.oasis-open.org/ns/bpel4people/ws-humantask/context/200803", "humanTaskRequestContext");
    private final static QName _BusinessAdministrators_QNAME = new QName("http://docs.oasis-open.org/ns/bpel4people/ws-humantask/context/200803", "businessAdministrators");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.oasis_open.docs.ns.bpel4people.ws_humantask.context._200803
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link TGenericHumanRole }
     * 
     */
    public TGenericHumanRole createTGenericHumanRole() {
        return new TGenericHumanRole();
    }

    /**
     * Create an instance of {@link THumanTaskResponseContext }
     * 
     */
    public THumanTaskResponseContext createTHumanTaskResponseContext() {
        return new THumanTaskResponseContext();
    }

    /**
     * Create an instance of {@link TPeopleAssignments }
     * 
     */
    public TPeopleAssignments createTPeopleAssignments() {
        return new TPeopleAssignments();
    }

    /**
     * Create an instance of {@link TAttachments }
     * 
     */
    public TAttachments createTAttachments() {
        return new TAttachments();
    }

    /**
     * Create an instance of {@link THumanTaskRequestContext }
     * 
     */
    public THumanTaskRequestContext createTHumanTaskRequestContext() {
        return new THumanTaskRequestContext();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TGenericHumanRole }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/context/200803", name = "taskInitiator", substitutionHeadNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/context/200803", substitutionHeadName = "genericHumanRole")
    public JAXBElement<TGenericHumanRole> createTaskInitiator(TGenericHumanRole value) {
        return new JAXBElement<TGenericHumanRole>(_TaskInitiator_QNAME, TGenericHumanRole.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TGenericHumanRole }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/context/200803", name = "recipients", substitutionHeadNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/context/200803", substitutionHeadName = "genericHumanRole")
    public JAXBElement<TGenericHumanRole> createRecipients(TGenericHumanRole value) {
        return new JAXBElement<TGenericHumanRole>(_Recipients_QNAME, TGenericHumanRole.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TGenericHumanRole }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/context/200803", name = "potentialOwners", substitutionHeadNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/context/200803", substitutionHeadName = "genericHumanRole")
    public JAXBElement<TGenericHumanRole> createPotentialOwners(TGenericHumanRole value) {
        return new JAXBElement<TGenericHumanRole>(_PotentialOwners_QNAME, TGenericHumanRole.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TGenericHumanRole }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/context/200803", name = "genericHumanRole")
    public JAXBElement<TGenericHumanRole> createGenericHumanRole(TGenericHumanRole value) {
        return new JAXBElement<TGenericHumanRole>(_GenericHumanRole_QNAME, TGenericHumanRole.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link THumanTaskResponseContext }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/context/200803", name = "humanTaskResponseContext")
    public JAXBElement<THumanTaskResponseContext> createHumanTaskResponseContext(THumanTaskResponseContext value) {
        return new JAXBElement<THumanTaskResponseContext>(_HumanTaskResponseContext_QNAME, THumanTaskResponseContext.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TGenericHumanRole }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/context/200803", name = "taskStakeholders", substitutionHeadNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/context/200803", substitutionHeadName = "genericHumanRole")
    public JAXBElement<TGenericHumanRole> createTaskStakeholders(TGenericHumanRole value) {
        return new JAXBElement<TGenericHumanRole>(_TaskStakeholders_QNAME, TGenericHumanRole.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TGenericHumanRole }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/context/200803", name = "excludedOwners", substitutionHeadNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/context/200803", substitutionHeadName = "genericHumanRole")
    public JAXBElement<TGenericHumanRole> createExcludedOwners(TGenericHumanRole value) {
        return new JAXBElement<TGenericHumanRole>(_ExcludedOwners_QNAME, TGenericHumanRole.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link THumanTaskRequestContext }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/context/200803", name = "humanTaskRequestContext")
    public JAXBElement<THumanTaskRequestContext> createHumanTaskRequestContext(THumanTaskRequestContext value) {
        return new JAXBElement<THumanTaskRequestContext>(_HumanTaskRequestContext_QNAME, THumanTaskRequestContext.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TGenericHumanRole }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/context/200803", name = "businessAdministrators", substitutionHeadNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/context/200803", substitutionHeadName = "genericHumanRole")
    public JAXBElement<TGenericHumanRole> createBusinessAdministrators(TGenericHumanRole value) {
        return new JAXBElement<TGenericHumanRole>(_BusinessAdministrators_QNAME, TGenericHumanRole.class, null, value);
    }

}
