//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.07.24 at 11:55:17 PM CEST 
//


package org.oasis_open.docs.ns.bpel4people.ws_humantask.context._200803;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import org.oasis_open.docs.ns.bpel4people.ws_humantask.types._200803.TAttachment;


/**
 * <p>Java class for tAttachments complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="tAttachments">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="returnAttachments" type="{http://docs.oasis-open.org/ns/bpel4people/ws-humantask/context/200803}tReturnAttachments" minOccurs="0"/>
 *         &lt;element ref="{http://docs.oasis-open.org/ns/bpel4people/ws-humantask/types/200803}attachment" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "tAttachments", propOrder = {
    "returnAttachments",
    "attachment"
})
public class TAttachments {

    protected TReturnAttachments returnAttachments;
    @XmlElement(namespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/types/200803")
    protected List<TAttachment> attachment;

    /**
     * Gets the value of the returnAttachments property.
     * 
     * @return
     *     possible object is
     *     {@link TReturnAttachments }
     *     
     */
    public TReturnAttachments getReturnAttachments() {
        return returnAttachments;
    }

    /**
     * Sets the value of the returnAttachments property.
     * 
     * @param value
     *     allowed object is
     *     {@link TReturnAttachments }
     *     
     */
    public void setReturnAttachments(TReturnAttachments value) {
        this.returnAttachments = value;
    }

    /**
     * Gets the value of the attachment property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the attachment property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAttachment().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TAttachment }
     * 
     * 
     */
    public List<TAttachment> getAttachment() {
        if (attachment == null) {
            attachment = new ArrayList<TAttachment>();
        }
        return this.attachment;
    }

}
