
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.example.claims;

import java.util.logging.Logger;
import javax.jws.Oneway;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.4.2
 * 2011-09-24T22:28:50.341+02:00
 * Generated source version: 2.4.2
 * 
 */

@javax.jws.WebService(
                      serviceName = "Service",
                      portName = "ClaimApprovalBinding",
                      targetNamespace = "http://www.example.com/claims",
                      endpointInterface = "com.example.claims.ClaimApprovalReminderPT")
                      
public class ClaimApprovalReminderPTImpl implements ClaimApprovalReminderPT {

    private static final Logger LOG = Logger.getLogger(ClaimApprovalReminderPTImpl.class.getName());

    /* (non-Javadoc)
     * @see com.example.claims.ClaimApprovalReminderPT#notify(java.lang.String  firstname ,)java.lang.String  lastname )*
     */
    public void notify(java.lang.String firstname,java.lang.String lastname) { 
        LOG.info("Executing operation notify");
        System.out.println(firstname);
        System.out.println(lastname);
        try {
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
