package org.oasis_open.docs.ns.bpel4people.ws_humantask.protocol._200803;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2-12/14/2009 02:16 PM(ramkris)-
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "protocolService", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/protocol/200803", wsdlLocation = "file:/F:/MAGISTERKA/workspace/WS-HT/src/main/resources/ws-humantask-protocol.wsdl")
public class ProtocolService
    extends Service
{

    private final static URL PROTOCOLSERVICE_WSDL_LOCATION;
    private final static WebServiceException PROTOCOLSERVICE_EXCEPTION;
    private final static QName PROTOCOLSERVICE_QNAME = new QName("http://docs.oasis-open.org/ns/bpel4people/ws-humantask/protocol/200803", "protocolService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/F:/MAGISTERKA/workspace/WS-HT/src/main/resources/ws-humantask-protocol.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        PROTOCOLSERVICE_WSDL_LOCATION = url;
        PROTOCOLSERVICE_EXCEPTION = e;
    }

    public ProtocolService() {
        super(__getWsdlLocation(), PROTOCOLSERVICE_QNAME);
    }

    public ProtocolService(WebServiceFeature... features) {
        super(__getWsdlLocation(), PROTOCOLSERVICE_QNAME); //features
    }

    public ProtocolService(URL wsdlLocation) {
        super(wsdlLocation, PROTOCOLSERVICE_QNAME);
    }

    public ProtocolService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, PROTOCOLSERVICE_QNAME); //features
    }

    public ProtocolService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ProtocolService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName); //features
    }

    /**
     * 
     * @return
     *     returns ClientParticipantPortType
     */
    @WebEndpoint(name = "portClientParticipant")
    public ClientParticipantPortType getPortClientParticipant() {
        return super.getPort(new QName("http://docs.oasis-open.org/ns/bpel4people/ws-humantask/protocol/200803", "portClientParticipant"), ClientParticipantPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ClientParticipantPortType
     */
    @WebEndpoint(name = "portClientParticipant")
    public ClientParticipantPortType getPortClientParticipant(WebServiceFeature... features) {
        return super.getPort(new QName("http://docs.oasis-open.org/ns/bpel4people/ws-humantask/protocol/200803", "portClientParticipant"), ClientParticipantPortType.class, features);
    }

    /**
     * 
     * @return
     *     returns HumanTaskParticipantPortType
     */
    @WebEndpoint(name = "portHumanParticipant")
    public HumanTaskParticipantPortType getPortHumanParticipant() {
        return super.getPort(new QName("http://docs.oasis-open.org/ns/bpel4people/ws-humantask/protocol/200803", "portHumanParticipant"), HumanTaskParticipantPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns HumanTaskParticipantPortType
     */
    @WebEndpoint(name = "portHumanParticipant")
    public HumanTaskParticipantPortType getPortHumanParticipant(WebServiceFeature... features) {
        return super.getPort(new QName("http://docs.oasis-open.org/ns/bpel4people/ws-humantask/protocol/200803", "portHumanParticipant"), HumanTaskParticipantPortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (PROTOCOLSERVICE_EXCEPTION!= null) {
            throw PROTOCOLSERVICE_EXCEPTION;
        }
        return PROTOCOLSERVICE_WSDL_LOCATION;
    }

}
