package com.example.claims;

import javax.jws.Oneway;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.4.2
 * 2011-09-24T22:28:50.391+02:00
 * Generated source version: 2.4.2
 * 
 */
@WebService(targetNamespace = "http://www.example.com/claims", name = "ClaimsHandlingPT")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface ClaimsHandlingPT {

    @Oneway
    @WebMethod(action = "http://www.example.com/claims/approve")
    public void approve(
        @WebParam(partName = "ClaimApprovalRequestApprove", name = "ClaimApprovalDataApprove", targetNamespace = "http://www.example.com/claims")
        ClaimApprovalData claimApprovalRequestApprove
    );

    @Oneway
    @WebMethod(action = "http://www.example.com/claims/escalate")
    public void escalate(
        @WebParam(partName = "ClaimApprovalRequestEscalate", name = "ClaimApprovalDataEscalate", targetNamespace = "http://www.example.com/claims")
        ClaimApprovalData claimApprovalRequestEscalate
    );
}
