
package com.example.claims;

import javax.xml.ws.Endpoint;

/**
 * This class was generated by Apache CXF 2.4.2
 * 2011-09-24T22:28:50.405+02:00
 * Generated source version: 2.4.2
 * 
 */
 
public class ClaimApprovalReminderPT_ClaimApprovalBinding_Server{

    protected ClaimApprovalReminderPT_ClaimApprovalBinding_Server() throws java.lang.Exception {
        System.out.println("Starting Server");
        Object implementor = new ClaimApprovalReminderPTImpl();
        String address = "http://www.example.com/";
        Endpoint.publish(address, implementor);
    }
    
    public static void main(String args[]) throws java.lang.Exception { 
        new ClaimApprovalReminderPT_ClaimApprovalBinding_Server();
        System.out.println("Server ready..."); 
        
        Thread.sleep(5 * 60 * 1000); 
        System.out.println("Server exiting");
        System.exit(0);
    }
}
