package com.example.claims;

import javax.jws.Oneway;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.4.2
 * 2011-09-24T22:28:50.382+02:00
 * Generated source version: 2.4.2
 * 
 */
@WebService(targetNamespace = "http://www.example.com/claims", name = "ClaimApprovalReminderPT")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface ClaimApprovalReminderPT {

    @Oneway
    @WebMethod(action = "http://www.example.com/claims/notify")
    public void notify(
        @WebParam(partName = "firstname", name = "firstname", targetNamespace = "")
        java.lang.String firstname,
        @WebParam(partName = "lastname", name = "lastname", targetNamespace = "")
        java.lang.String lastname
    );
}
