
package org.oasis_open.docs.ns.bpel4people.ws_humantask.leantask.api._200803;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2-12/14/2009 02:16 PM(ramkris)-
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "LeanTaskService", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/leantask/api/200803", wsdlLocation = "file:/F:/MAGISTERKA/workspace/WS-HT/src/main/resources/ws-humantask-leantask-api.wsdl")
public class LeanTaskService
    extends Service
{

    private final static URL LEANTASKSERVICE_WSDL_LOCATION;
    private final static WebServiceException LEANTASKSERVICE_EXCEPTION;
    private final static QName LEANTASKSERVICE_QNAME = new QName("http://docs.oasis-open.org/ns/bpel4people/ws-humantask/leantask/api/200803", "LeanTaskService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/F:/MAGISTERKA/workspace/WS-HT/src/main/resources/ws-humantask-leantask-api.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        LEANTASKSERVICE_WSDL_LOCATION = url;
        LEANTASKSERVICE_EXCEPTION = e;
    }

    public LeanTaskService() {
        super(__getWsdlLocation(), LEANTASKSERVICE_QNAME);
    }

    public LeanTaskService(WebServiceFeature... features) {
        super(__getWsdlLocation(), LEANTASKSERVICE_QNAME); //features
    }

    public LeanTaskService(URL wsdlLocation) {
        super(wsdlLocation, LEANTASKSERVICE_QNAME);
    }

    public LeanTaskService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, LEANTASKSERVICE_QNAME); //features
    }

    public LeanTaskService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public LeanTaskService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName); //features
    }

    /**
     * 
     * @return
     *     returns LeanTaskCallbackOperations
     */
    @WebEndpoint(name = "portLeanTaskCallbackOperations")
    public LeanTaskCallbackOperations getPortLeanTaskCallbackOperations() {
        return super.getPort(new QName("http://docs.oasis-open.org/ns/bpel4people/ws-humantask/leantask/api/200803", "portLeanTaskCallbackOperations"), LeanTaskCallbackOperations.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns LeanTaskCallbackOperations
     */
    @WebEndpoint(name = "portLeanTaskCallbackOperations")
    public LeanTaskCallbackOperations getPortLeanTaskCallbackOperations(WebServiceFeature... features) {
        return super.getPort(new QName("http://docs.oasis-open.org/ns/bpel4people/ws-humantask/leantask/api/200803", "portLeanTaskCallbackOperations"), LeanTaskCallbackOperations.class, features);
    }

    /**
     * 
     * @return
     *     returns LeanTaskOperations
     */
    @WebEndpoint(name = "leanTaskOperations")
    public LeanTaskOperations getLeanTaskOperations() {
        return super.getPort(new QName("http://docs.oasis-open.org/ns/bpel4people/ws-humantask/leantask/api/200803", "leanTaskOperations"), LeanTaskOperations.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns LeanTaskOperations
     */
    @WebEndpoint(name = "leanTaskOperations")
    public LeanTaskOperations getLeanTaskOperations(WebServiceFeature... features) {
        return super.getPort(new QName("http://docs.oasis-open.org/ns/bpel4people/ws-humantask/leantask/api/200803", "leanTaskOperations"), LeanTaskOperations.class, features);
    }

    private static URL __getWsdlLocation() {
        if (LEANTASKSERVICE_EXCEPTION!= null) {
            throw LEANTASKSERVICE_EXCEPTION;
        }
        return LEANTASKSERVICE_WSDL_LOCATION;
    }

}
