package com.example.claims;

import javax.jws.Oneway;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.ws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.BindingType;

/**
 * This class was generated by Apache CXF 2.4.2
 * 2011-09-24T22:28:50.373+02:00
 * Generated source version: 2.4.2
 * 
 */
@WebService(targetNamespace = "http://www.example.com/claims", name = "ClaimsHandlingCallbackPT")
@XmlSeeAlso({ObjectFactory.class})
@javax.jws.soap.SOAPBinding(parameterStyle = javax.jws.soap.SOAPBinding.ParameterStyle.BARE)
public interface ClaimsHandlingCallbackPT {

    @Oneway
    @WebMethod(action = "http://www.example.com/claims/approvalResponse")
    public void approvalResponse(
        @WebParam(partName = "ClaimApprovalResponse", name = "ClaimApprovalResponse", targetNamespace = "")
        boolean claimApprovalResponse
    );
}
