
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.example.claims;

import java.util.logging.Logger;
import javax.jws.Oneway;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.4.2
 * 2011-09-24T22:28:50.356+02:00
 * Generated source version: 2.4.2
 * 
 */

@javax.jws.WebService(
                      serviceName = "Service",
                      portName = "ClaimHendlingPort",
                      targetNamespace = "http://www.example.com/claims",
                      endpointInterface = "com.example.claims.ClaimsHandlingPT")
                      
public class ClaimsHandlingPTImpl implements ClaimsHandlingPT {

    private static final Logger LOG = Logger.getLogger(ClaimsHandlingPTImpl.class.getName());

    /* (non-Javadoc)
     * @see com.example.claims.ClaimsHandlingPT#approve(com.example.claims.ClaimApprovalData  claimApprovalRequestApprove )*
     */
    public void approve(ClaimApprovalData claimApprovalRequestApprove) { 
        LOG.info("Executing operation approve");
        System.out.println(claimApprovalRequestApprove);
        try {
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.example.claims.ClaimsHandlingPT#escalate(com.example.claims.ClaimApprovalData  claimApprovalRequestEscalate )*
     */
    public void escalate(ClaimApprovalData claimApprovalRequestEscalate) { 
        LOG.info("Executing operation escalate");
        System.out.println(claimApprovalRequestEscalate);
        try {
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
