
package org.oasis_open.docs.ns.bpel4people.ws_humantask.api._200803;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.namespace.QName;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import org.oasis_open.docs.ns.bpel4people.ws_humantask.types._200803.TAttachment;
import org.oasis_open.docs.ns.bpel4people.ws_humantask.types._200803.TAttachmentInfo;
import org.oasis_open.docs.ns.bpel4people.ws_humantask.types._200803.TComment;
import org.oasis_open.docs.ns.bpel4people.ws_humantask.types._200803.TFault;
import org.oasis_open.docs.ns.bpel4people.ws_humantask.types._200803.TOrganizationalEntity;
import org.oasis_open.docs.ns.bpel4people.ws_humantask.types._200803.TRenderingTypes;
import org.oasis_open.docs.ns.bpel4people.ws_humantask.types._200803.TTaskAbstract;
import org.oasis_open.docs.ns.bpel4people.ws_humantask.types._200803.TTaskDetails;
import org.oasis_open.docs.ns.bpel4people.ws_humantask.types._200803.TTaskInstanceData;
import org.oasis_open.docs.ns.bpel4people.ws_humantask.types._200803.TTaskOperations;
import org.oasis_open.docs.ns.bpel4people.ws_humantask.types._200803.TTaskQueryResultSet;
import org.oasis_open.docs.ns.bpel4people.ws_humantask.types._200803.TTime;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2-12/14/2009 02:16 PM(ramkris)-
 * Generated source version: 2.2
 * 
 */
@WebService(name = "taskOperations", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803")
@XmlSeeAlso({
    org.oasis_open.docs.ns.bpel4people.ws_humantask.api._200803.ObjectFactory.class,
    org.oasis_open.docs.ns.bpel4people.ws_humantask.types._200803.ObjectFactory.class
})
public interface TaskOperations {


    /**
     * 
     * @param taskIdentifier
     * @param name
     * @param attachment
     * @param contentType
     * @param accessType
     * @return
     *     returns java.lang.String
     * @throws IllegalOperationFault
     * @throws IllegalStateFault
     * @throws IllegalArgumentFault
     * @throws IllegalAccessFault
     */
    @WebMethod(action = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803/addAttachment")
    @WebResult(name = "identifier", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803")
    @RequestWrapper(localName = "addAttachment", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803", className = "org.oasis_open.docs.ns.bpel4people.ws_humantask.api._200803.AddAttachment")
    @ResponseWrapper(localName = "addAttachmentResponse", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803", className = "org.oasis_open.docs.ns.bpel4people.ws_humantask.api._200803.AddAttachmentResponse")
    public String addAttachment(
        @WebParam(name = "taskIdentifier", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803")
        String taskIdentifier,
        @WebParam(name = "name", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803")
        String name,
        @WebParam(name = "accessType", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803")
        String accessType,
        @WebParam(name = "contentType", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803")
        String contentType,
        @WebParam(name = "attachment", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803")
        Object attachment)
        throws IllegalAccessFault, IllegalArgumentFault, IllegalOperationFault, IllegalStateFault
    ;

    /**
     * 
     * @param text
     * @param identifier
     * @return
     *     returns java.lang.String
     * @throws IllegalOperationFault
     * @throws IllegalStateFault
     * @throws IllegalArgumentFault
     * @throws IllegalAccessFault
     */
    @WebMethod(action = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803/addComment")
    @WebResult(name = "commentID", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803")
    @RequestWrapper(localName = "addComment", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803", className = "org.oasis_open.docs.ns.bpel4people.ws_humantask.api._200803.AddComment")
    @ResponseWrapper(localName = "addCommentResponse", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803", className = "org.oasis_open.docs.ns.bpel4people.ws_humantask.api._200803.AddCommentResponse")
    public String addComment(
        @WebParam(name = "identifier", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803")
        String identifier,
        @WebParam(name = "text", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803")
        String text)
        throws IllegalAccessFault, IllegalArgumentFault, IllegalOperationFault, IllegalStateFault
    ;

    /**
     * 
     * @param identifier
     * @throws IllegalOperationFault
     * @throws IllegalStateFault
     * @throws IllegalArgumentFault
     * @throws IllegalAccessFault
     */
    @WebMethod(action = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803/claim")
    @RequestWrapper(localName = "claim", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803", className = "org.oasis_open.docs.ns.bpel4people.ws_humantask.api._200803.Claim")
    @ResponseWrapper(localName = "claimResponse", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803", className = "org.oasis_open.docs.ns.bpel4people.ws_humantask.api._200803.ClaimResponse")
    public void claim(
        @WebParam(name = "identifier", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803")
        String identifier)
        throws IllegalAccessFault, IllegalArgumentFault, IllegalOperationFault, IllegalStateFault
    ;

    /**
     * 
     * @param identifier
     * @return
     *     returns java.util.List<org.oasis_open.docs.ns.bpel4people.ws_humantask.api._200803.TBatchResponse>
     */
    @WebMethod(action = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803/batchClaim")
    @WebResult(name = "batchResponse", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803")
    @RequestWrapper(localName = "batchClaim", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803", className = "org.oasis_open.docs.ns.bpel4people.ws_humantask.api._200803.BatchClaim")
    @ResponseWrapper(localName = "batchClaimResponse", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803", className = "org.oasis_open.docs.ns.bpel4people.ws_humantask.api._200803.BatchClaimResponse")
    public List<TBatchResponse> batchClaim(
        @WebParam(name = "identifier", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803")
        List<String> identifier);

    /**
     * 
     * @param identifier
     * @param taskData
     * @throws IllegalOperationFault
     * @throws IllegalStateFault
     * @throws IllegalArgumentFault
     * @throws IllegalAccessFault
     */
    @WebMethod(action = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803/complete")
    @RequestWrapper(localName = "complete", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803", className = "org.oasis_open.docs.ns.bpel4people.ws_humantask.api._200803.Complete")
    @ResponseWrapper(localName = "completeResponse", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803", className = "org.oasis_open.docs.ns.bpel4people.ws_humantask.api._200803.CompleteResponse")
    public void complete(
        @WebParam(name = "identifier", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803")
        String identifier,
        @WebParam(name = "taskData", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803")
        Object taskData)
        throws IllegalAccessFault, IllegalArgumentFault, IllegalOperationFault, IllegalStateFault
    ;

    /**
     * 
     * @param identifier
     * @param taskData
     * @return
     *     returns java.util.List<org.oasis_open.docs.ns.bpel4people.ws_humantask.api._200803.TBatchResponse>
     */
    @WebMethod(action = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803/batchComplete")
    @WebResult(name = "batchResponse", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803")
    @RequestWrapper(localName = "batchComplete", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803", className = "org.oasis_open.docs.ns.bpel4people.ws_humantask.api._200803.BatchComplete")
    @ResponseWrapper(localName = "batchCompleteResponse", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803", className = "org.oasis_open.docs.ns.bpel4people.ws_humantask.api._200803.BatchCompleteResponse")
    public List<TBatchResponse> batchComplete(
        @WebParam(name = "identifier", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803")
        List<String> identifier,
        @WebParam(name = "taskData", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803")
        Object taskData);

    /**
     * 
     * @param organizationalEntity
     * @param identifier
     * @throws IllegalOperationFault
     * @throws IllegalStateFault
     * @throws IllegalArgumentFault
     * @throws IllegalAccessFault
     * @throws RecipientNotAllowed
     */
    @WebMethod(action = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803/delegate")
    @RequestWrapper(localName = "delegate", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803", className = "org.oasis_open.docs.ns.bpel4people.ws_humantask.api._200803.Delegate")
    @ResponseWrapper(localName = "delegateResponse", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803", className = "org.oasis_open.docs.ns.bpel4people.ws_humantask.api._200803.DelegateResponse")
    public void delegate(
        @WebParam(name = "identifier", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803")
        String identifier,
        @WebParam(name = "organizationalEntity", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803")
        TOrganizationalEntity organizationalEntity)
        throws IllegalAccessFault, IllegalArgumentFault, IllegalOperationFault, IllegalStateFault, RecipientNotAllowed
    ;

    /**
     * 
     * @param organizationalEntity
     * @param identifier
     * @return
     *     returns java.util.List<org.oasis_open.docs.ns.bpel4people.ws_humantask.api._200803.TBatchResponse>
     */
    @WebMethod(action = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803/batchDelegate")
    @WebResult(name = "batchResponse", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803")
    @RequestWrapper(localName = "batchDelegate", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803", className = "org.oasis_open.docs.ns.bpel4people.ws_humantask.api._200803.BatchDelegate")
    @ResponseWrapper(localName = "batchDelegateResponse", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803", className = "org.oasis_open.docs.ns.bpel4people.ws_humantask.api._200803.BatchDelegateResponse")
    public List<TBatchResponse> batchDelegate(
        @WebParam(name = "identifier", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803")
        List<String> identifier,
        @WebParam(name = "organizationalEntity", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803")
        TOrganizationalEntity organizationalEntity);

    /**
     * 
     * @param taskIdentifier
     * @param attachmentIdentifier
     * @throws IllegalOperationFault
     * @throws IllegalStateFault
     * @throws IllegalArgumentFault
     * @throws IllegalAccessFault
     */
    @WebMethod(action = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803/deleteAttachment")
    @RequestWrapper(localName = "deleteAttachment", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803", className = "org.oasis_open.docs.ns.bpel4people.ws_humantask.api._200803.DeleteAttachment")
    @ResponseWrapper(localName = "deleteAttachmentResponse", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803", className = "org.oasis_open.docs.ns.bpel4people.ws_humantask.api._200803.DeleteAttachmentResponse")
    public void deleteAttachment(
        @WebParam(name = "taskIdentifier", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803")
        String taskIdentifier,
        @WebParam(name = "attachmentIdentifier", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803")
        String attachmentIdentifier)
        throws IllegalAccessFault, IllegalArgumentFault, IllegalOperationFault, IllegalStateFault
    ;

    /**
     * 
     * @param taskIdentifier
     * @param commentIdentifier
     * @throws IllegalOperationFault
     * @throws IllegalStateFault
     * @throws IllegalArgumentFault
     * @throws IllegalAccessFault
     */
    @WebMethod(action = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803/deleteComment")
    @RequestWrapper(localName = "deleteComment", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803", className = "org.oasis_open.docs.ns.bpel4people.ws_humantask.api._200803.DeleteComment")
    @ResponseWrapper(localName = "deleteCommentResponse", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803", className = "org.oasis_open.docs.ns.bpel4people.ws_humantask.api._200803.DeleteCommentResponse")
    public void deleteComment(
        @WebParam(name = "taskIdentifier", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803")
        String taskIdentifier,
        @WebParam(name = "commentIdentifier", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803")
        String commentIdentifier)
        throws IllegalAccessFault, IllegalArgumentFault, IllegalOperationFault, IllegalStateFault
    ;

    /**
     * 
     * @param identifier
     * @throws IllegalOperationFault
     * @throws IllegalStateFault
     * @throws IllegalArgumentFault
     * @throws IllegalAccessFault
     */
    @WebMethod(action = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803/deleteFault")
    @RequestWrapper(localName = "deleteFault", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803", className = "org.oasis_open.docs.ns.bpel4people.ws_humantask.api._200803.DeleteFault")
    @ResponseWrapper(localName = "deleteFaultResponse", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803", className = "org.oasis_open.docs.ns.bpel4people.ws_humantask.api._200803.DeleteFaultResponse")
    public void deleteFault(
        @WebParam(name = "identifier", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803")
        String identifier)
        throws IllegalAccessFault, IllegalArgumentFault, IllegalOperationFault, IllegalStateFault
    ;

    /**
     * 
     * @param identifier
     * @throws IllegalOperationFault
     * @throws IllegalStateFault
     * @throws IllegalArgumentFault
     * @throws IllegalAccessFault
     */
    @WebMethod(action = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803/deleteOutput")
    @RequestWrapper(localName = "deleteOutput", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803", className = "org.oasis_open.docs.ns.bpel4people.ws_humantask.api._200803.DeleteOutput")
    @ResponseWrapper(localName = "deleteOutputResponse", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803", className = "org.oasis_open.docs.ns.bpel4people.ws_humantask.api._200803.DeleteOutputResponse")
    public void deleteOutput(
        @WebParam(name = "identifier", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803")
        String identifier)
        throws IllegalAccessFault, IllegalArgumentFault, IllegalOperationFault, IllegalStateFault
    ;

    /**
     * 
     * @param fault
     * @param identifier
     * @throws IllegalOperationFault
     * @throws IllegalStateFault
     * @throws IllegalArgumentFault
     * @throws IllegalAccessFault
     */
    @WebMethod(action = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803/fail")
    @RequestWrapper(localName = "fail", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803", className = "org.oasis_open.docs.ns.bpel4people.ws_humantask.api._200803.Fail")
    @ResponseWrapper(localName = "failResponse", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803", className = "org.oasis_open.docs.ns.bpel4people.ws_humantask.api._200803.FailResponse")
    public void fail(
        @WebParam(name = "identifier", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803")
        String identifier,
        @WebParam(name = "fault", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803")
        TFault fault)
        throws IllegalAccessFault, IllegalArgumentFault, IllegalOperationFault, IllegalStateFault
    ;

    /**
     * 
     * @param fault
     * @param identifier
     * @return
     *     returns java.util.List<org.oasis_open.docs.ns.bpel4people.ws_humantask.api._200803.TBatchResponse>
     */
    @WebMethod(action = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803/batchFail")
    @WebResult(name = "batchResponse", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803")
    @RequestWrapper(localName = "batchFail", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803", className = "org.oasis_open.docs.ns.bpel4people.ws_humantask.api._200803.BatchFail")
    @ResponseWrapper(localName = "batchFailResponse", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803", className = "org.oasis_open.docs.ns.bpel4people.ws_humantask.api._200803.BatchFailResponse")
    public List<TBatchResponse> batchFail(
        @WebParam(name = "identifier", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803")
        List<String> identifier,
        @WebParam(name = "fault", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803")
        TFault fault);

    /**
     * 
     * @param organizationalEntity
     * @param identifier
     * @throws IllegalOperationFault
     * @throws IllegalStateFault
     * @throws IllegalArgumentFault
     * @throws IllegalAccessFault
     */
    @WebMethod(action = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803/forward")
    @RequestWrapper(localName = "forward", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803", className = "org.oasis_open.docs.ns.bpel4people.ws_humantask.api._200803.Forward")
    @ResponseWrapper(localName = "forwardResponse", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803", className = "org.oasis_open.docs.ns.bpel4people.ws_humantask.api._200803.ForwardResponse")
    public void forward(
        @WebParam(name = "identifier", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803")
        String identifier,
        @WebParam(name = "organizationalEntity", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803")
        TOrganizationalEntity organizationalEntity)
        throws IllegalAccessFault, IllegalArgumentFault, IllegalOperationFault, IllegalStateFault
    ;

    /**
     * 
     * @param organizationalEntity
     * @param identifier
     * @return
     *     returns java.util.List<org.oasis_open.docs.ns.bpel4people.ws_humantask.api._200803.TBatchResponse>
     */
    @WebMethod(action = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803/batchForward")
    @WebResult(name = "batchResponse", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803")
    @RequestWrapper(localName = "batchForward", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803", className = "org.oasis_open.docs.ns.bpel4people.ws_humantask.api._200803.BatchForward")
    @ResponseWrapper(localName = "batchForwardResponse", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803", className = "org.oasis_open.docs.ns.bpel4people.ws_humantask.api._200803.BatchForwardResponse")
    public List<TBatchResponse> batchForward(
        @WebParam(name = "identifier", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803")
        List<String> identifier,
        @WebParam(name = "organizationalEntity", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803")
        TOrganizationalEntity organizationalEntity);

    /**
     * 
     * @param taskIdentifier
     * @param attachmentIdentifier
     * @return
     *     returns java.util.List<org.oasis_open.docs.ns.bpel4people.ws_humantask.types._200803.TAttachment>
     * @throws IllegalOperationFault
     * @throws IllegalStateFault
     * @throws IllegalArgumentFault
     * @throws IllegalAccessFault
     */
    @WebMethod(action = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803/getAttachment")
    @WebResult(name = "attachment", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803")
    @RequestWrapper(localName = "getAttachment", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803", className = "org.oasis_open.docs.ns.bpel4people.ws_humantask.api._200803.GetAttachment")
    @ResponseWrapper(localName = "getAttachmentResponse", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803", className = "org.oasis_open.docs.ns.bpel4people.ws_humantask.api._200803.GetAttachmentResponse")
    public List<TAttachment> getAttachment(
        @WebParam(name = "taskIdentifier", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803")
        String taskIdentifier,
        @WebParam(name = "attachmentIdentifier", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803")
        String attachmentIdentifier)
        throws IllegalAccessFault, IllegalArgumentFault, IllegalOperationFault, IllegalStateFault
    ;

    /**
     * 
     * @param identifier
     * @return
     *     returns java.util.List<org.oasis_open.docs.ns.bpel4people.ws_humantask.types._200803.TAttachmentInfo>
     * @throws IllegalOperationFault
     * @throws IllegalStateFault
     * @throws IllegalArgumentFault
     * @throws IllegalAccessFault
     */
    @WebMethod(action = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803/getAttachmentInfos")
    @WebResult(name = "info", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803")
    @RequestWrapper(localName = "getAttachmentInfos", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803", className = "org.oasis_open.docs.ns.bpel4people.ws_humantask.api._200803.GetAttachmentInfos")
    @ResponseWrapper(localName = "getAttachmentInfosResponse", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803", className = "org.oasis_open.docs.ns.bpel4people.ws_humantask.api._200803.GetAttachmentInfosResponse")
    public List<TAttachmentInfo> getAttachmentInfos(
        @WebParam(name = "identifier", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803")
        String identifier)
        throws IllegalAccessFault, IllegalArgumentFault, IllegalOperationFault, IllegalStateFault
    ;

    /**
     * 
     * @param identifier
     * @return
     *     returns java.util.List<org.oasis_open.docs.ns.bpel4people.ws_humantask.types._200803.TComment>
     * @throws IllegalOperationFault
     * @throws IllegalStateFault
     * @throws IllegalArgumentFault
     * @throws IllegalAccessFault
     */
    @WebMethod(action = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803/getComments")
    @WebResult(name = "comment", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803")
    @RequestWrapper(localName = "getComments", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803", className = "org.oasis_open.docs.ns.bpel4people.ws_humantask.api._200803.GetComments")
    @ResponseWrapper(localName = "getCommentsResponse", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803", className = "org.oasis_open.docs.ns.bpel4people.ws_humantask.api._200803.GetCommentsResponse")
    public List<TComment> getComments(
        @WebParam(name = "identifier", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803")
        String identifier)
        throws IllegalAccessFault, IllegalArgumentFault, IllegalOperationFault, IllegalStateFault
    ;

    /**
     * 
     * @param identifier
     * @return
     *     returns org.oasis_open.docs.ns.bpel4people.ws_humantask.types._200803.TFault
     * @throws IllegalOperationFault
     * @throws IllegalStateFault
     * @throws IllegalArgumentFault
     * @throws IllegalAccessFault
     */
    @WebMethod(action = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803/getFault")
    @WebResult(name = "fault", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803")
    @RequestWrapper(localName = "getFault", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803", className = "org.oasis_open.docs.ns.bpel4people.ws_humantask.api._200803.GetFault")
    @ResponseWrapper(localName = "getFaultResponse", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803", className = "org.oasis_open.docs.ns.bpel4people.ws_humantask.api._200803.GetFaultResponse")
    public TFault getFault(
        @WebParam(name = "identifier", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803")
        String identifier)
        throws IllegalAccessFault, IllegalArgumentFault, IllegalOperationFault, IllegalStateFault
    ;

    /**
     * 
     * @param part
     * @param identifier
     * @return
     *     returns java.lang.Object
     * @throws IllegalOperationFault
     * @throws IllegalStateFault
     * @throws IllegalArgumentFault
     * @throws IllegalAccessFault
     */
    @WebMethod(action = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803/getInput")
    @WebResult(name = "taskData", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803")
    @RequestWrapper(localName = "getInput", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803", className = "org.oasis_open.docs.ns.bpel4people.ws_humantask.api._200803.GetInput")
    @ResponseWrapper(localName = "getInputResponse", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803", className = "org.oasis_open.docs.ns.bpel4people.ws_humantask.api._200803.GetInputResponse")
    public Object getInput(
        @WebParam(name = "identifier", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803")
        String identifier,
        @WebParam(name = "part", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803")
        String part)
        throws IllegalAccessFault, IllegalArgumentFault, IllegalOperationFault, IllegalStateFault
    ;

    /**
     * 
     * @param identifier
     * @return
     *     returns java.lang.String
     * @throws IllegalOperationFault
     * @throws IllegalArgumentFault
     */
    @WebMethod(action = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803/getOutcome")
    @WebResult(name = "outcome", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803")
    @RequestWrapper(localName = "getOutcome", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803", className = "org.oasis_open.docs.ns.bpel4people.ws_humantask.api._200803.GetOutcome")
    @ResponseWrapper(localName = "getOutcomeResponse", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803", className = "org.oasis_open.docs.ns.bpel4people.ws_humantask.api._200803.GetOutcomeResponse")
    public String getOutcome(
        @WebParam(name = "identifier", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803")
        String identifier)
        throws IllegalArgumentFault, IllegalOperationFault
    ;

    /**
     * 
     * @param part
     * @param identifier
     * @return
     *     returns java.lang.Object
     * @throws IllegalOperationFault
     * @throws IllegalStateFault
     * @throws IllegalArgumentFault
     * @throws IllegalAccessFault
     */
    @WebMethod(action = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803/getOutput")
    @WebResult(name = "taskData", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803")
    @RequestWrapper(localName = "getOutput", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803", className = "org.oasis_open.docs.ns.bpel4people.ws_humantask.api._200803.GetOutput")
    @ResponseWrapper(localName = "getOutputResponse", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803", className = "org.oasis_open.docs.ns.bpel4people.ws_humantask.api._200803.GetOutputResponse")
    public Object getOutput(
        @WebParam(name = "identifier", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803")
        String identifier,
        @WebParam(name = "part", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803")
        String part)
        throws IllegalAccessFault, IllegalArgumentFault, IllegalOperationFault, IllegalStateFault
    ;

    /**
     * 
     * @param taskIdentifier
     * @return
     *     returns org.oasis_open.docs.ns.bpel4people.ws_humantask.types._200803.TTaskDetails
     * @throws IllegalOperationFault
     * @throws IllegalStateFault
     * @throws IllegalArgumentFault
     * @throws IllegalAccessFault
     */
    @WebMethod(action = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803/getParentTask")
    @WebResult(name = "parentTask", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803")
    @RequestWrapper(localName = "getParentTask", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803", className = "org.oasis_open.docs.ns.bpel4people.ws_humantask.api._200803.GetParentTask")
    @ResponseWrapper(localName = "getParentTaskResponse", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803", className = "org.oasis_open.docs.ns.bpel4people.ws_humantask.api._200803.GetParentTaskResponse")
    public TTaskDetails getParentTask(
        @WebParam(name = "taskIdentifier", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803")
        String taskIdentifier)
        throws IllegalAccessFault, IllegalArgumentFault, IllegalOperationFault, IllegalStateFault
    ;

    /**
     * 
     * @param taskIdentifier
     * @return
     *     returns java.lang.String
     * @throws IllegalOperationFault
     * @throws IllegalStateFault
     * @throws IllegalArgumentFault
     * @throws IllegalAccessFault
     */
    @WebMethod(action = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803/getParentTaskIdentifier")
    @WebResult(name = "parentTaskIdentifier", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803")
    @RequestWrapper(localName = "getParentTaskIdentifier", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803", className = "org.oasis_open.docs.ns.bpel4people.ws_humantask.api._200803.GetParentTaskIdentifier")
    @ResponseWrapper(localName = "getParentTaskIdentifierResponse", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803", className = "org.oasis_open.docs.ns.bpel4people.ws_humantask.api._200803.GetParentTaskIdentifierResponse")
    public String getParentTaskIdentifier(
        @WebParam(name = "taskIdentifier", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803")
        String taskIdentifier)
        throws IllegalAccessFault, IllegalArgumentFault, IllegalOperationFault, IllegalStateFault
    ;

    /**
     * 
     * @param renderingType
     * @param identifier
     * @return
     *     returns java.lang.Object
     * @throws IllegalArgumentFault
     */
    @WebMethod(action = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803/getRendering")
    @WebResult(name = "rendering", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803")
    @RequestWrapper(localName = "getRendering", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803", className = "org.oasis_open.docs.ns.bpel4people.ws_humantask.api._200803.GetRendering")
    @ResponseWrapper(localName = "getRenderingResponse", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803", className = "org.oasis_open.docs.ns.bpel4people.ws_humantask.api._200803.GetRenderingResponse")
    public Object getRendering(
        @WebParam(name = "identifier", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803")
        String identifier,
        @WebParam(name = "renderingType", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803")
        QName renderingType)
        throws IllegalArgumentFault
    ;

    /**
     * 
     * @param identifier
     * @return
     *     returns java.util.List<javax.xml.namespace.QName>
     * @throws IllegalArgumentFault
     */
    @WebMethod(action = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803/getRenderingTypes")
    @WebResult(name = "renderingType", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803")
    @RequestWrapper(localName = "getRenderingTypes", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803", className = "org.oasis_open.docs.ns.bpel4people.ws_humantask.api._200803.GetRenderingTypes")
    @ResponseWrapper(localName = "getRenderingTypesResponse", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803", className = "org.oasis_open.docs.ns.bpel4people.ws_humantask.api._200803.GetRenderingTypesResponse")
    public List<QName> getRenderingTypes(
        @WebParam(name = "identifier", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803")
        String identifier)
        throws IllegalArgumentFault
    ;

    /**
     * 
     * @param taskIdentifier
     * @return
     *     returns java.util.List<java.lang.String>
     * @throws IllegalOperationFault
     * @throws IllegalStateFault
     * @throws IllegalArgumentFault
     * @throws IllegalAccessFault
     */
    @WebMethod(action = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803/getSubtaskIdentifiers")
    @WebResult(name = "subtaskIdentifier", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803")
    @RequestWrapper(localName = "getSubtaskIdentifiers", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803", className = "org.oasis_open.docs.ns.bpel4people.ws_humantask.api._200803.GetSubtaskIdentifiers")
    @ResponseWrapper(localName = "getSubtaskIdentifiersResponse", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803", className = "org.oasis_open.docs.ns.bpel4people.ws_humantask.api._200803.GetSubtaskIdentifiersResponse")
    public List<String> getSubtaskIdentifiers(
        @WebParam(name = "taskIdentifier", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803")
        String taskIdentifier)
        throws IllegalAccessFault, IllegalArgumentFault, IllegalOperationFault, IllegalStateFault
    ;

    /**
     * 
     * @param taskIdentifier
     * @return
     *     returns java.util.List<org.oasis_open.docs.ns.bpel4people.ws_humantask.types._200803.TTaskDetails>
     * @throws IllegalOperationFault
     * @throws IllegalStateFault
     * @throws IllegalArgumentFault
     * @throws IllegalAccessFault
     */
    @WebMethod(action = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803/getSubtasks")
    @WebResult(name = "subtask", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803")
    @RequestWrapper(localName = "getSubtasks", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803", className = "org.oasis_open.docs.ns.bpel4people.ws_humantask.api._200803.GetSubtasks")
    @ResponseWrapper(localName = "getSubtasksResponse", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803", className = "org.oasis_open.docs.ns.bpel4people.ws_humantask.api._200803.GetSubtasksResponse")
    public List<TTaskDetails> getSubtasks(
        @WebParam(name = "taskIdentifier", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803")
        String taskIdentifier)
        throws IllegalAccessFault, IllegalArgumentFault, IllegalOperationFault, IllegalStateFault
    ;

    /**
     * 
     * @param contentType
     * @param identifier
     * @return
     *     returns java.lang.String
     * @throws IllegalArgumentFault
     */
    @WebMethod(action = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803/getTaskDescription")
    @WebResult(name = "description", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803")
    @RequestWrapper(localName = "getTaskDescription", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803", className = "org.oasis_open.docs.ns.bpel4people.ws_humantask.api._200803.GetTaskDescription")
    @ResponseWrapper(localName = "getTaskDescriptionResponse", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803", className = "org.oasis_open.docs.ns.bpel4people.ws_humantask.api._200803.GetTaskDescriptionResponse")
    public String getTaskDescription(
        @WebParam(name = "identifier", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803")
        String identifier,
        @WebParam(name = "contentType", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803")
        String contentType)
        throws IllegalArgumentFault
    ;

    /**
     * 
     * @param identifier
     * @return
     *     returns org.oasis_open.docs.ns.bpel4people.ws_humantask.types._200803.TTaskDetails
     * @throws IllegalArgumentFault
     */
    @WebMethod(action = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803/getTaskDetails")
    @WebResult(name = "taskDetails", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803")
    @RequestWrapper(localName = "getTaskDetails", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803", className = "org.oasis_open.docs.ns.bpel4people.ws_humantask.api._200803.GetTaskDetails")
    @ResponseWrapper(localName = "getTaskDetailsResponse", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803", className = "org.oasis_open.docs.ns.bpel4people.ws_humantask.api._200803.GetTaskDetailsResponse")
    public TTaskDetails getTaskDetails(
        @WebParam(name = "identifier", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803")
        String identifier)
        throws IllegalArgumentFault
    ;

    /**
     * 
     * @param getTaskHistory
     * @return
     *     returns org.oasis_open.docs.ns.bpel4people.ws_humantask.api._200803.GetTaskHistoryResponse
     * @throws IllegalOperationFault
     * @throws IllegalArgumentFault
     * @throws IllegalAccessFault
     */
    @WebMethod(action = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803/getTaskHistory")
    @WebResult(name = "getTaskHistoryResponse", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803", partName = "getTaskHistoryResponse")
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    public GetTaskHistoryResponse getTaskHistory(
        @WebParam(name = "getTaskHistory", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803", partName = "getTaskHistory")
        GetTaskHistory getTaskHistory)
        throws IllegalAccessFault, IllegalArgumentFault, IllegalOperationFault
    ;

    /**
     * 
     * @param renderingPreferences
     * @param properties
     * @param identifier
     * @return
     *     returns org.oasis_open.docs.ns.bpel4people.ws_humantask.types._200803.TTaskInstanceData
     * @throws IllegalOperationFault
     * @throws IllegalArgumentFault
     * @throws IllegalAccessFault
     */
    @WebMethod(action = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803/getTaskInstanceData")
    @WebResult(name = "taskInstanceData", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803")
    @RequestWrapper(localName = "getTaskInstanceData", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803", className = "org.oasis_open.docs.ns.bpel4people.ws_humantask.api._200803.GetTaskInstanceData")
    @ResponseWrapper(localName = "getTaskInstanceDataResponse", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803", className = "org.oasis_open.docs.ns.bpel4people.ws_humantask.api._200803.GetTaskInstanceDataResponse")
    public TTaskInstanceData getTaskInstanceData(
        @WebParam(name = "identifier", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803")
        String identifier,
        @WebParam(name = "properties", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803")
        String properties,
        @WebParam(name = "renderingPreferences", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803")
        List<TRenderingTypes> renderingPreferences)
        throws IllegalAccessFault, IllegalArgumentFault, IllegalOperationFault
    ;

    /**
     * 
     * @param identifier
     * @return
     *     returns org.oasis_open.docs.ns.bpel4people.ws_humantask.types._200803.TTaskOperations
     * @throws IllegalOperationFault
     * @throws IllegalArgumentFault
     */
    @WebMethod(action = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803/getTaskOperations")
    @WebResult(name = "taskOperations", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803")
    @RequestWrapper(localName = "getTaskOperations", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803", className = "org.oasis_open.docs.ns.bpel4people.ws_humantask.api._200803.GetTaskOperations")
    @ResponseWrapper(localName = "getTaskOperationsResponse", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803", className = "org.oasis_open.docs.ns.bpel4people.ws_humantask.api._200803.GetTaskOperationsResponse")
    public TTaskOperations getTaskOperations(
        @WebParam(name = "identifier", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803")
        String identifier)
        throws IllegalArgumentFault, IllegalOperationFault
    ;

    /**
     * 
     * @param taskIdentifier
     * @return
     *     returns boolean
     * @throws IllegalOperationFault
     * @throws IllegalStateFault
     * @throws IllegalArgumentFault
     * @throws IllegalAccessFault
     */
    @WebMethod(action = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803/hasSubtasks")
    @WebResult(name = "result", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803")
    @RequestWrapper(localName = "hasSubtasks", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803", className = "org.oasis_open.docs.ns.bpel4people.ws_humantask.api._200803.HasSubtasks")
    @ResponseWrapper(localName = "hasSubtasksResponse", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803", className = "org.oasis_open.docs.ns.bpel4people.ws_humantask.api._200803.HasSubtasksResponse")
    public boolean hasSubtasks(
        @WebParam(name = "taskIdentifier", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803")
        String taskIdentifier)
        throws IllegalAccessFault, IllegalArgumentFault, IllegalOperationFault, IllegalStateFault
    ;

    /**
     * 
     * @param taskIdentifier
     * @param name
     * @return
     *     returns java.lang.String
     * @throws IllegalOperationFault
     * @throws IllegalStateFault
     * @throws IllegalArgumentFault
     * @throws IllegalAccessFault
     */
    @WebMethod(action = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803/instantiateSubtask")
    @WebResult(name = "subtaskIdentifier", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803")
    @RequestWrapper(localName = "instantiateSubtask", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803", className = "org.oasis_open.docs.ns.bpel4people.ws_humantask.api._200803.InstantiateSubtask")
    @ResponseWrapper(localName = "instantiateSubtaskResponse", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803", className = "org.oasis_open.docs.ns.bpel4people.ws_humantask.api._200803.InstantiateSubtaskResponse")
    public String instantiateSubtask(
        @WebParam(name = "taskIdentifier", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803")
        String taskIdentifier,
        @WebParam(name = "name", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803")
        String name)
        throws IllegalAccessFault, IllegalArgumentFault, IllegalOperationFault, IllegalStateFault
    ;

    /**
     * 
     * @param taskIdentifier
     * @return
     *     returns boolean
     * @throws IllegalOperationFault
     * @throws IllegalStateFault
     * @throws IllegalArgumentFault
     * @throws IllegalAccessFault
     */
    @WebMethod(action = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803/isSubtask")
    @WebResult(name = "result", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803")
    @RequestWrapper(localName = "isSubtask", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803", className = "org.oasis_open.docs.ns.bpel4people.ws_humantask.api._200803.IsSubtask")
    @ResponseWrapper(localName = "isSubtaskResponse", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803", className = "org.oasis_open.docs.ns.bpel4people.ws_humantask.api._200803.IsSubtaskResponse")
    public boolean isSubtask(
        @WebParam(name = "taskIdentifier", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803")
        String taskIdentifier)
        throws IllegalAccessFault, IllegalArgumentFault, IllegalOperationFault, IllegalStateFault
    ;

    /**
     * 
     * @param identifier
     * @throws IllegalOperationFault
     * @throws IllegalStateFault
     * @throws IllegalArgumentFault
     * @throws IllegalAccessFault
     */
    @WebMethod(action = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803/release")
    @RequestWrapper(localName = "release", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803", className = "org.oasis_open.docs.ns.bpel4people.ws_humantask.api._200803.Release")
    @ResponseWrapper(localName = "releaseResponse", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803", className = "org.oasis_open.docs.ns.bpel4people.ws_humantask.api._200803.ReleaseResponse")
    public void release(
        @WebParam(name = "identifier", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803")
        String identifier)
        throws IllegalAccessFault, IllegalArgumentFault, IllegalOperationFault, IllegalStateFault
    ;

    /**
     * 
     * @param identifier
     * @return
     *     returns java.util.List<org.oasis_open.docs.ns.bpel4people.ws_humantask.api._200803.TBatchResponse>
     */
    @WebMethod(action = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803/batchRelease")
    @WebResult(name = "batchResponse", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803")
    @RequestWrapper(localName = "batchRelease", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803", className = "org.oasis_open.docs.ns.bpel4people.ws_humantask.api._200803.BatchRelease")
    @ResponseWrapper(localName = "batchReleaseResponse", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803", className = "org.oasis_open.docs.ns.bpel4people.ws_humantask.api._200803.BatchReleaseResponse")
    public List<TBatchResponse> batchRelease(
        @WebParam(name = "identifier", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803")
        List<String> identifier);

    /**
     * 
     * @param identifier
     * @throws IllegalOperationFault
     * @throws IllegalArgumentFault
     * @throws IllegalAccessFault
     */
    @WebMethod(action = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803/remove")
    @RequestWrapper(localName = "remove", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803", className = "org.oasis_open.docs.ns.bpel4people.ws_humantask.api._200803.Remove")
    @ResponseWrapper(localName = "removeResponse", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803", className = "org.oasis_open.docs.ns.bpel4people.ws_humantask.api._200803.RemoveResponse")
    public void remove(
        @WebParam(name = "identifier", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803")
        String identifier)
        throws IllegalAccessFault, IllegalArgumentFault, IllegalOperationFault
    ;

    /**
     * 
     * @param identifier
     * @return
     *     returns java.util.List<org.oasis_open.docs.ns.bpel4people.ws_humantask.api._200803.TBatchResponse>
     */
    @WebMethod(action = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803/batchRemove")
    @WebResult(name = "batchResponse", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803")
    @RequestWrapper(localName = "batchRemove", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803", className = "org.oasis_open.docs.ns.bpel4people.ws_humantask.api._200803.BatchRemove")
    @ResponseWrapper(localName = "batchRemoveResponse", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803", className = "org.oasis_open.docs.ns.bpel4people.ws_humantask.api._200803.BatchRemoveResponse")
    public List<TBatchResponse> batchRemove(
        @WebParam(name = "identifier", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803")
        List<String> identifier);

    /**
     * 
     * @param identifier
     * @throws IllegalOperationFault
     * @throws IllegalStateFault
     * @throws IllegalArgumentFault
     * @throws IllegalAccessFault
     */
    @WebMethod(action = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803/resume")
    @RequestWrapper(localName = "resume", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803", className = "org.oasis_open.docs.ns.bpel4people.ws_humantask.api._200803.Resume")
    @ResponseWrapper(localName = "resumeResponse", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803", className = "org.oasis_open.docs.ns.bpel4people.ws_humantask.api._200803.ResumeResponse")
    public void resume(
        @WebParam(name = "identifier", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803")
        String identifier)
        throws IllegalAccessFault, IllegalArgumentFault, IllegalOperationFault, IllegalStateFault
    ;

    /**
     * 
     * @param identifier
     * @return
     *     returns java.util.List<org.oasis_open.docs.ns.bpel4people.ws_humantask.api._200803.TBatchResponse>
     */
    @WebMethod(action = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803/batchResume")
    @WebResult(name = "batchResponse", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803")
    @RequestWrapper(localName = "batchResume", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803", className = "org.oasis_open.docs.ns.bpel4people.ws_humantask.api._200803.BatchResume")
    @ResponseWrapper(localName = "batchResumeResponse", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803", className = "org.oasis_open.docs.ns.bpel4people.ws_humantask.api._200803.BatchResumeResponse")
    public List<TBatchResponse> batchResume(
        @WebParam(name = "identifier", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803")
        List<String> identifier);

    /**
     * 
     * @param fault
     * @param identifier
     * @throws IllegalOperationFault
     * @throws IllegalStateFault
     * @throws IllegalArgumentFault
     * @throws IllegalAccessFault
     */
    @WebMethod(action = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803/setFault")
    @RequestWrapper(localName = "setFault", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803", className = "org.oasis_open.docs.ns.bpel4people.ws_humantask.api._200803.SetFault")
    @ResponseWrapper(localName = "setFaultResponse", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803", className = "org.oasis_open.docs.ns.bpel4people.ws_humantask.api._200803.SetFaultResponse")
    public void setFault(
        @WebParam(name = "identifier", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803")
        String identifier,
        @WebParam(name = "fault", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803")
        TFault fault)
        throws IllegalAccessFault, IllegalArgumentFault, IllegalOperationFault, IllegalStateFault
    ;

    /**
     * 
     * @param part
     * @param identifier
     * @param taskData
     * @throws IllegalOperationFault
     * @throws IllegalStateFault
     * @throws IllegalArgumentFault
     * @throws IllegalAccessFault
     */
    @WebMethod(action = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803/setOutput")
    @RequestWrapper(localName = "setOutput", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803", className = "org.oasis_open.docs.ns.bpel4people.ws_humantask.api._200803.SetOutput")
    @ResponseWrapper(localName = "setOutputResponse", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803", className = "org.oasis_open.docs.ns.bpel4people.ws_humantask.api._200803.SetOutputResponse")
    public void setOutput(
        @WebParam(name = "identifier", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803")
        String identifier,
        @WebParam(name = "part", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803")
        String part,
        @WebParam(name = "taskData", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803")
        Object taskData)
        throws IllegalAccessFault, IllegalArgumentFault, IllegalOperationFault, IllegalStateFault
    ;

    /**
     * 
     * @param priority
     * @param identifier
     * @throws IllegalOperationFault
     * @throws IllegalStateFault
     * @throws IllegalArgumentFault
     * @throws IllegalAccessFault
     */
    @WebMethod(action = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803/setPriority")
    @RequestWrapper(localName = "setPriority", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803", className = "org.oasis_open.docs.ns.bpel4people.ws_humantask.api._200803.SetPriority")
    @ResponseWrapper(localName = "setPriorityResponse", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803", className = "org.oasis_open.docs.ns.bpel4people.ws_humantask.api._200803.SetPriorityResponse")
    public void setPriority(
        @WebParam(name = "identifier", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803")
        String identifier,
        @WebParam(name = "priority", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803")
        int priority)
        throws IllegalAccessFault, IllegalArgumentFault, IllegalOperationFault, IllegalStateFault
    ;

    /**
     * 
     * @param priority
     * @param identifier
     * @return
     *     returns java.util.List<org.oasis_open.docs.ns.bpel4people.ws_humantask.api._200803.TBatchResponse>
     */
    @WebMethod(action = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803/batchSetPriority")
    @WebResult(name = "batchResponse", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803")
    @RequestWrapper(localName = "batchSetPriority", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803", className = "org.oasis_open.docs.ns.bpel4people.ws_humantask.api._200803.BatchSetPriority")
    @ResponseWrapper(localName = "batchSetPriorityResponse", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803", className = "org.oasis_open.docs.ns.bpel4people.ws_humantask.api._200803.BatchSetPriorityResponse")
    public List<TBatchResponse> batchSetPriority(
        @WebParam(name = "identifier", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803")
        List<String> identifier,
        @WebParam(name = "priority", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803")
        int priority);

    /**
     * 
     * @param deadlineName
     * @param deadlineExpression
     * @param identifier
     * @throws IllegalOperationFault
     * @throws IllegalStateFault
     * @throws IllegalArgumentFault
     * @throws IllegalAccessFault
     */
    @WebMethod(action = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803/setTaskCompletionDeadlineExpression")
    @RequestWrapper(localName = "setTaskCompletionDeadlineExpression", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803", className = "org.oasis_open.docs.ns.bpel4people.ws_humantask.api._200803.SetTaskCompletionDeadlineExpression")
    @ResponseWrapper(localName = "setTaskCompletionDeadlineExpressionResponse", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803", className = "org.oasis_open.docs.ns.bpel4people.ws_humantask.api._200803.SetTaskCompletionDeadlineExpressionResponse")
    public void setTaskCompletionDeadlineExpression(
        @WebParam(name = "identifier", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803")
        String identifier,
        @WebParam(name = "deadlineName", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803")
        String deadlineName,
        @WebParam(name = "deadlineExpression", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803")
        String deadlineExpression)
        throws IllegalAccessFault, IllegalArgumentFault, IllegalOperationFault, IllegalStateFault
    ;

    /**
     * 
     * @param deadlineName
     * @param durationExpression
     * @param identifier
     * @throws IllegalOperationFault
     * @throws IllegalStateFault
     * @throws IllegalArgumentFault
     * @throws IllegalAccessFault
     */
    @WebMethod(action = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803/setTaskCompletionDurationExpression")
    @RequestWrapper(localName = "setTaskCompletionDurationExpression", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803", className = "org.oasis_open.docs.ns.bpel4people.ws_humantask.api._200803.SetTaskCompletionDurationExpression")
    @ResponseWrapper(localName = "setTaskCompletionDurationExpressionResponse", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803", className = "org.oasis_open.docs.ns.bpel4people.ws_humantask.api._200803.SetTaskCompletionDurationExpressionResponse")
    public void setTaskCompletionDurationExpression(
        @WebParam(name = "identifier", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803")
        String identifier,
        @WebParam(name = "deadlineName", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803")
        String deadlineName,
        @WebParam(name = "durationExpression", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803")
        String durationExpression)
        throws IllegalAccessFault, IllegalArgumentFault, IllegalOperationFault, IllegalStateFault
    ;

    /**
     * 
     * @param deadlineName
     * @param deadlineExpression
     * @param identifier
     * @throws IllegalOperationFault
     * @throws IllegalStateFault
     * @throws IllegalArgumentFault
     * @throws IllegalAccessFault
     */
    @WebMethod(action = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803/setTaskStartDeadlineExpression")
    @RequestWrapper(localName = "setTaskStartDeadlineExpression", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803", className = "org.oasis_open.docs.ns.bpel4people.ws_humantask.api._200803.SetTaskStartDeadlineExpression")
    @ResponseWrapper(localName = "setTaskStartDeadlineExpressionResponse", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803", className = "org.oasis_open.docs.ns.bpel4people.ws_humantask.api._200803.SetTaskStartDeadlineExpressionResponse")
    public void setTaskStartDeadlineExpression(
        @WebParam(name = "identifier", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803")
        String identifier,
        @WebParam(name = "deadlineName", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803")
        String deadlineName,
        @WebParam(name = "deadlineExpression", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803")
        String deadlineExpression)
        throws IllegalAccessFault, IllegalArgumentFault, IllegalOperationFault, IllegalStateFault
    ;

    /**
     * 
     * @param deadlineName
     * @param durationExpression
     * @param identifier
     * @throws IllegalOperationFault
     * @throws IllegalStateFault
     * @throws IllegalArgumentFault
     * @throws IllegalAccessFault
     */
    @WebMethod(action = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803/setTaskStartDurationExpression")
    @RequestWrapper(localName = "setTaskStartDurationExpression", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803", className = "org.oasis_open.docs.ns.bpel4people.ws_humantask.api._200803.SetTaskStartDurationExpression")
    @ResponseWrapper(localName = "setTaskStartDurationExpressionResponse", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803", className = "org.oasis_open.docs.ns.bpel4people.ws_humantask.api._200803.SetTaskStartDurationExpressionResponse")
    public void setTaskStartDurationExpression(
        @WebParam(name = "identifier", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803")
        String identifier,
        @WebParam(name = "deadlineName", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803")
        String deadlineName,
        @WebParam(name = "durationExpression", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803")
        String durationExpression)
        throws IllegalAccessFault, IllegalArgumentFault, IllegalOperationFault, IllegalStateFault
    ;

    /**
     * 
     * @param identifier
     * @throws IllegalOperationFault
     * @throws IllegalStateFault
     * @throws IllegalArgumentFault
     * @throws IllegalAccessFault
     */
    @WebMethod(action = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803/skip")
    @RequestWrapper(localName = "skip", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803", className = "org.oasis_open.docs.ns.bpel4people.ws_humantask.api._200803.Skip")
    @ResponseWrapper(localName = "skipResponse", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803", className = "org.oasis_open.docs.ns.bpel4people.ws_humantask.api._200803.SkipResponse")
    public void skip(
        @WebParam(name = "identifier", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803")
        String identifier)
        throws IllegalAccessFault, IllegalArgumentFault, IllegalOperationFault, IllegalStateFault
    ;

    /**
     * 
     * @param identifier
     * @return
     *     returns java.util.List<org.oasis_open.docs.ns.bpel4people.ws_humantask.api._200803.TBatchResponse>
     */
    @WebMethod(action = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803/batchSkip")
    @WebResult(name = "batchResponse", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803")
    @RequestWrapper(localName = "batchSkip", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803", className = "org.oasis_open.docs.ns.bpel4people.ws_humantask.api._200803.BatchSkip")
    @ResponseWrapper(localName = "batchSkipResponse", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803", className = "org.oasis_open.docs.ns.bpel4people.ws_humantask.api._200803.BatchSkipResponse")
    public List<TBatchResponse> batchSkip(
        @WebParam(name = "identifier", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803")
        List<String> identifier);

    /**
     * 
     * @param identifier
     * @throws IllegalOperationFault
     * @throws IllegalStateFault
     * @throws IllegalArgumentFault
     * @throws IllegalAccessFault
     */
    @WebMethod(action = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803/start")
    @RequestWrapper(localName = "start", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803", className = "org.oasis_open.docs.ns.bpel4people.ws_humantask.api._200803.Start")
    @ResponseWrapper(localName = "startResponse", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803", className = "org.oasis_open.docs.ns.bpel4people.ws_humantask.api._200803.StartResponse")
    public void start(
        @WebParam(name = "identifier", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803")
        String identifier)
        throws IllegalAccessFault, IllegalArgumentFault, IllegalOperationFault, IllegalStateFault
    ;

    /**
     * 
     * @param identifier
     * @return
     *     returns java.util.List<org.oasis_open.docs.ns.bpel4people.ws_humantask.api._200803.TBatchResponse>
     */
    @WebMethod(action = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803/batchStart")
    @WebResult(name = "batchResponse", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803")
    @RequestWrapper(localName = "batchStart", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803", className = "org.oasis_open.docs.ns.bpel4people.ws_humantask.api._200803.BatchStart")
    @ResponseWrapper(localName = "batchStartResponse", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803", className = "org.oasis_open.docs.ns.bpel4people.ws_humantask.api._200803.BatchStartResponse")
    public List<TBatchResponse> batchStart(
        @WebParam(name = "identifier", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803")
        List<String> identifier);

    /**
     * 
     * @param identifier
     * @throws IllegalOperationFault
     * @throws IllegalStateFault
     * @throws IllegalArgumentFault
     * @throws IllegalAccessFault
     */
    @WebMethod(action = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803/stop")
    @RequestWrapper(localName = "stop", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803", className = "org.oasis_open.docs.ns.bpel4people.ws_humantask.api._200803.Stop")
    @ResponseWrapper(localName = "stopResponse", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803", className = "org.oasis_open.docs.ns.bpel4people.ws_humantask.api._200803.StopResponse")
    public void stop(
        @WebParam(name = "identifier", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803")
        String identifier)
        throws IllegalAccessFault, IllegalArgumentFault, IllegalOperationFault, IllegalStateFault
    ;

    /**
     * 
     * @param identifier
     * @return
     *     returns java.util.List<org.oasis_open.docs.ns.bpel4people.ws_humantask.api._200803.TBatchResponse>
     */
    @WebMethod(action = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803/batchStop")
    @WebResult(name = "batchResponse", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803")
    @RequestWrapper(localName = "batchStop", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803", className = "org.oasis_open.docs.ns.bpel4people.ws_humantask.api._200803.BatchStop")
    @ResponseWrapper(localName = "batchStopResponse", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803", className = "org.oasis_open.docs.ns.bpel4people.ws_humantask.api._200803.BatchStopResponse")
    public List<TBatchResponse> batchStop(
        @WebParam(name = "identifier", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803")
        List<String> identifier);

    /**
     * 
     * @param identifier
     * @throws IllegalOperationFault
     * @throws IllegalStateFault
     * @throws IllegalArgumentFault
     * @throws IllegalAccessFault
     */
    @WebMethod(action = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803/suspend")
    @RequestWrapper(localName = "suspend", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803", className = "org.oasis_open.docs.ns.bpel4people.ws_humantask.api._200803.Suspend")
    @ResponseWrapper(localName = "suspendResponse", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803", className = "org.oasis_open.docs.ns.bpel4people.ws_humantask.api._200803.SuspendResponse")
    public void suspend(
        @WebParam(name = "identifier", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803")
        String identifier)
        throws IllegalAccessFault, IllegalArgumentFault, IllegalOperationFault, IllegalStateFault
    ;

    /**
     * 
     * @param identifier
     * @return
     *     returns java.util.List<org.oasis_open.docs.ns.bpel4people.ws_humantask.api._200803.TBatchResponse>
     */
    @WebMethod(action = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803/batchSuspend")
    @WebResult(name = "batchResponse", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803")
    @RequestWrapper(localName = "batchSuspend", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803", className = "org.oasis_open.docs.ns.bpel4people.ws_humantask.api._200803.BatchSuspend")
    @ResponseWrapper(localName = "batchSuspendResponse", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803", className = "org.oasis_open.docs.ns.bpel4people.ws_humantask.api._200803.BatchSuspendResponse")
    public List<TBatchResponse> batchSuspend(
        @WebParam(name = "identifier", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803")
        List<String> identifier);

    /**
     * 
     * @param time
     * @param identifier
     * @throws IllegalOperationFault
     * @throws IllegalStateFault
     * @throws IllegalArgumentFault
     * @throws IllegalAccessFault
     */
    @WebMethod(action = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803/suspendUntil")
    @RequestWrapper(localName = "suspendUntil", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803", className = "org.oasis_open.docs.ns.bpel4people.ws_humantask.api._200803.SuspendUntil")
    @ResponseWrapper(localName = "suspendUntilResponse", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803", className = "org.oasis_open.docs.ns.bpel4people.ws_humantask.api._200803.SuspendUntilResponse")
    public void suspendUntil(
        @WebParam(name = "identifier", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803")
        String identifier,
        @WebParam(name = "time", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803")
        TTime time)
        throws IllegalAccessFault, IllegalArgumentFault, IllegalOperationFault, IllegalStateFault
    ;

    /**
     * 
     * @param time
     * @param identifier
     * @return
     *     returns java.util.List<org.oasis_open.docs.ns.bpel4people.ws_humantask.api._200803.TBatchResponse>
     */
    @WebMethod(action = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803/batchSuspendUntil")
    @WebResult(name = "batchResponse", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803")
    @RequestWrapper(localName = "batchSuspendUntil", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803", className = "org.oasis_open.docs.ns.bpel4people.ws_humantask.api._200803.BatchSuspendUntil")
    @ResponseWrapper(localName = "batchSuspendUntilResponse", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803", className = "org.oasis_open.docs.ns.bpel4people.ws_humantask.api._200803.BatchSuspendUntilResponse")
    public List<TBatchResponse> batchSuspendUntil(
        @WebParam(name = "identifier", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803")
        List<String> identifier,
        @WebParam(name = "time", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803")
        TTime time);

    /**
     * 
     * @param text
     * @param taskIdentifier
     * @param commentIdentifier
     * @throws IllegalOperationFault
     * @throws IllegalStateFault
     * @throws IllegalArgumentFault
     * @throws IllegalAccessFault
     */
    @WebMethod(action = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803/updateComment")
    @RequestWrapper(localName = "updateComment", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803", className = "org.oasis_open.docs.ns.bpel4people.ws_humantask.api._200803.UpdateComment")
    @ResponseWrapper(localName = "updateCommentResponse", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803", className = "org.oasis_open.docs.ns.bpel4people.ws_humantask.api._200803.UpdateCommentResponse")
    public void updateComment(
        @WebParam(name = "taskIdentifier", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803")
        String taskIdentifier,
        @WebParam(name = "commentIdentifier", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803")
        String commentIdentifier,
        @WebParam(name = "text", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803")
        String text)
        throws IllegalAccessFault, IllegalArgumentFault, IllegalOperationFault, IllegalStateFault
    ;

    /**
     * 
     * @param whereClause
     * @param maxTasks
     * @param createdOnClause
     * @param workQueue
     * @param genericHumanRole
     * @param taskIndexOffset
     * @param status
     * @param taskType
     * @param orderByClause
     * @return
     *     returns java.util.List<org.oasis_open.docs.ns.bpel4people.ws_humantask.types._200803.TTaskAbstract>
     * @throws IllegalOperationFault
     * @throws IllegalStateFault
     * @throws IllegalArgumentFault
     */
    @WebMethod(action = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803/getMyTaskAbstracts")
    @WebResult(name = "taskAbstract", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803")
    @RequestWrapper(localName = "getMyTaskAbstracts", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803", className = "org.oasis_open.docs.ns.bpel4people.ws_humantask.api._200803.GetMyTaskAbstracts")
    @ResponseWrapper(localName = "getMyTaskAbstractsResponse", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803", className = "org.oasis_open.docs.ns.bpel4people.ws_humantask.api._200803.GetMyTaskAbstractsResponse")
    public List<TTaskAbstract> getMyTaskAbstracts(
        @WebParam(name = "taskType", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803")
        String taskType,
        @WebParam(name = "genericHumanRole", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803")
        String genericHumanRole,
        @WebParam(name = "workQueue", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803")
        String workQueue,
        @WebParam(name = "status", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803")
        List<String> status,
        @WebParam(name = "whereClause", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803")
        String whereClause,
        @WebParam(name = "orderByClause", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803")
        String orderByClause,
        @WebParam(name = "createdOnClause", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803")
        String createdOnClause,
        @WebParam(name = "maxTasks", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803")
        Integer maxTasks,
        @WebParam(name = "taskIndexOffset", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803")
        Integer taskIndexOffset)
        throws IllegalArgumentFault, IllegalOperationFault, IllegalStateFault
    ;

    /**
     * 
     * @param whereClause
     * @param maxTasks
     * @param createdOnClause
     * @param workQueue
     * @param genericHumanRole
     * @param taskIndexOffset
     * @param status
     * @param taskType
     * @param orderByClause
     * @return
     *     returns java.util.List<org.oasis_open.docs.ns.bpel4people.ws_humantask.types._200803.TTaskDetails>
     * @throws IllegalOperationFault
     * @throws IllegalStateFault
     * @throws IllegalArgumentFault
     */
    @WebMethod(action = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803/getMyTaskDetails")
    @WebResult(name = "taskDetails", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803")
    @RequestWrapper(localName = "getMyTaskDetails", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803", className = "org.oasis_open.docs.ns.bpel4people.ws_humantask.api._200803.GetMyTaskDetails")
    @ResponseWrapper(localName = "getMyTaskDetailsResponse", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803", className = "org.oasis_open.docs.ns.bpel4people.ws_humantask.api._200803.GetMyTaskDetailsResponse")
    public List<TTaskDetails> getMyTaskDetails(
        @WebParam(name = "taskType", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803")
        String taskType,
        @WebParam(name = "genericHumanRole", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803")
        String genericHumanRole,
        @WebParam(name = "workQueue", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803")
        String workQueue,
        @WebParam(name = "status", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803")
        List<String> status,
        @WebParam(name = "whereClause", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803")
        String whereClause,
        @WebParam(name = "orderByClause", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803")
        String orderByClause,
        @WebParam(name = "createdOnClause", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803")
        String createdOnClause,
        @WebParam(name = "maxTasks", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803")
        Integer maxTasks,
        @WebParam(name = "taskIndexOffset", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803")
        Integer taskIndexOffset)
        throws IllegalArgumentFault, IllegalOperationFault, IllegalStateFault
    ;

    /**
     * 
     * @param whereClause
     * @param maxTasks
     * @param taskIndexOffset
     * @param orderByClause
     * @param selectClause
     * @return
     *     returns org.oasis_open.docs.ns.bpel4people.ws_humantask.types._200803.TTaskQueryResultSet
     * @throws IllegalStateFault
     * @throws IllegalArgumentFault
     */
    @WebMethod(action = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803/query")
    @WebResult(name = "taskQueryResultSet", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803")
    @RequestWrapper(localName = "query", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803", className = "org.oasis_open.docs.ns.bpel4people.ws_humantask.api._200803.Query")
    @ResponseWrapper(localName = "queryResponse", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803", className = "org.oasis_open.docs.ns.bpel4people.ws_humantask.api._200803.QueryResponse")
    public TTaskQueryResultSet query(
        @WebParam(name = "selectClause", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803")
        String selectClause,
        @WebParam(name = "whereClause", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803")
        String whereClause,
        @WebParam(name = "orderByClause", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803")
        String orderByClause,
        @WebParam(name = "maxTasks", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803")
        Integer maxTasks,
        @WebParam(name = "taskIndexOffset", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803")
        Integer taskIndexOffset)
        throws IllegalArgumentFault, IllegalStateFault
    ;

    /**
     * 
     * @param identifier
     * @throws IllegalOperationFault
     * @throws IllegalStateFault
     * @throws IllegalArgumentFault
     * @throws IllegalAccessFault
     */
    @WebMethod(action = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803/activate")
    @RequestWrapper(localName = "activate", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803", className = "org.oasis_open.docs.ns.bpel4people.ws_humantask.api._200803.Activate")
    @ResponseWrapper(localName = "activateResponse", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803", className = "org.oasis_open.docs.ns.bpel4people.ws_humantask.api._200803.ActivateResponse")
    public void activate(
        @WebParam(name = "identifier", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803")
        String identifier)
        throws IllegalAccessFault, IllegalArgumentFault, IllegalOperationFault, IllegalStateFault
    ;

    /**
     * 
     * @param identifier
     * @return
     *     returns java.util.List<org.oasis_open.docs.ns.bpel4people.ws_humantask.api._200803.TBatchResponse>
     */
    @WebMethod(action = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803/batchActivate")
    @WebResult(name = "batchResponse", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803")
    @RequestWrapper(localName = "batchActivate", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803", className = "org.oasis_open.docs.ns.bpel4people.ws_humantask.api._200803.BatchActivate")
    @ResponseWrapper(localName = "batchActivateResponse", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803", className = "org.oasis_open.docs.ns.bpel4people.ws_humantask.api._200803.BatchActivateResponse")
    public List<TBatchResponse> batchActivate(
        @WebParam(name = "identifier", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803")
        List<String> identifier);

    /**
     * 
     * @param organizationalEntity
     * @param identifier
     * @throws IllegalOperationFault
     * @throws IllegalStateFault
     * @throws IllegalArgumentFault
     * @throws IllegalAccessFault
     */
    @WebMethod(action = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803/nominate")
    @RequestWrapper(localName = "nominate", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803", className = "org.oasis_open.docs.ns.bpel4people.ws_humantask.api._200803.Nominate")
    @ResponseWrapper(localName = "nominateResponse", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803", className = "org.oasis_open.docs.ns.bpel4people.ws_humantask.api._200803.NominateResponse")
    public void nominate(
        @WebParam(name = "identifier", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803")
        String identifier,
        @WebParam(name = "organizationalEntity", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803")
        TOrganizationalEntity organizationalEntity)
        throws IllegalAccessFault, IllegalArgumentFault, IllegalOperationFault, IllegalStateFault
    ;

    /**
     * 
     * @param identifier
     * @return
     *     returns java.util.List<org.oasis_open.docs.ns.bpel4people.ws_humantask.api._200803.TBatchResponse>
     */
    @WebMethod(action = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803/batchNominate")
    @WebResult(name = "batchResponse", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803")
    @RequestWrapper(localName = "batchNominate", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803", className = "org.oasis_open.docs.ns.bpel4people.ws_humantask.api._200803.BatchNominate")
    @ResponseWrapper(localName = "batchNominateResponse", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803", className = "org.oasis_open.docs.ns.bpel4people.ws_humantask.api._200803.BatchNominateResponse")
    public List<TBatchResponse> batchNominate(
        @WebParam(name = "identifier", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803")
        List<String> identifier);

    /**
     * 
     * @param genericHumanRole
     * @param organizationalEntity
     * @param identifier
     * @throws IllegalOperationFault
     * @throws IllegalStateFault
     * @throws IllegalArgumentFault
     * @throws IllegalAccessFault
     */
    @WebMethod(action = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803/setGenericHumanRole")
    @RequestWrapper(localName = "setGenericHumanRole", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803", className = "org.oasis_open.docs.ns.bpel4people.ws_humantask.api._200803.SetGenericHumanRole")
    @ResponseWrapper(localName = "setGenericHumanRoleResponse", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803", className = "org.oasis_open.docs.ns.bpel4people.ws_humantask.api._200803.SetGenericHumanRoleResponse")
    public void setGenericHumanRole(
        @WebParam(name = "identifier", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803")
        String identifier,
        @WebParam(name = "genericHumanRole", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803")
        String genericHumanRole,
        @WebParam(name = "organizationalEntity", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803")
        TOrganizationalEntity organizationalEntity)
        throws IllegalAccessFault, IllegalArgumentFault, IllegalOperationFault, IllegalStateFault
    ;

    /**
     * 
     * @param genericHumanRole
     * @param organizationalEntity
     * @param identifier
     * @return
     *     returns java.util.List<org.oasis_open.docs.ns.bpel4people.ws_humantask.api._200803.TBatchResponse>
     */
    @WebMethod(action = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803/batchSetGenericHumanRole")
    @WebResult(name = "batchResponse", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803")
    @RequestWrapper(localName = "batchSetGenericHumanRole", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803", className = "org.oasis_open.docs.ns.bpel4people.ws_humantask.api._200803.BatchSetGenericHumanRole")
    @ResponseWrapper(localName = "batchSetGenericHumanRoleResponse", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803", className = "org.oasis_open.docs.ns.bpel4people.ws_humantask.api._200803.BatchSetGenericHumanRoleResponse")
    public List<TBatchResponse> batchSetGenericHumanRole(
        @WebParam(name = "identifier", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803")
        List<String> identifier,
        @WebParam(name = "genericHumanRole", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803")
        String genericHumanRole,
        @WebParam(name = "organizationalEntity", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803")
        TOrganizationalEntity organizationalEntity);

}
