
package org.oasis_open.docs.ns.bpel4people.ws_humantask.api._200803;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2-12/14/2009 02:16 PM(ramkris)-
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "TaskService", targetNamespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803", wsdlLocation = "file:/F:/MAGISTERKA/workspace/WS-HT/src/main/resources/ws-humantask-api.wsdl")
public class TaskService
    extends Service
{

    private final static URL TASKSERVICE_WSDL_LOCATION;
    private final static WebServiceException TASKSERVICE_EXCEPTION;
    private final static QName TASKSERVICE_QNAME = new QName("http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803", "TaskService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/F:/MAGISTERKA/workspace/WS-HT/src/main/resources/ws-humantask-api.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        TASKSERVICE_WSDL_LOCATION = url;
        TASKSERVICE_EXCEPTION = e;
    }

    public TaskService() {
        super(__getWsdlLocation(), TASKSERVICE_QNAME);
    }

    public TaskService(WebServiceFeature... features) {
        super(__getWsdlLocation(), TASKSERVICE_QNAME); //features
    }

    public TaskService(URL wsdlLocation) {
        super(wsdlLocation, TASKSERVICE_QNAME);
    }

    public TaskService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, TASKSERVICE_QNAME); //features
    }

    public TaskService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public TaskService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName); //features
    }

    /**
     * 
     * @return
     *     returns TaskOperations
     */
    @WebEndpoint(name = "portService")
    public TaskOperations getPortService() {
        return super.getPort(new QName("http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803", "portService"), TaskOperations.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns TaskOperations
     */
    @WebEndpoint(name = "portService")
    public TaskOperations getPortService(WebServiceFeature... features) {
        return super.getPort(new QName("http://docs.oasis-open.org/ns/bpel4people/ws-humantask/api/200803", "portService"), TaskOperations.class, features);
    }

    private static URL __getWsdlLocation() {
        if (TASKSERVICE_EXCEPTION!= null) {
            throw TASKSERVICE_EXCEPTION;
        }
        return TASKSERVICE_WSDL_LOCATION;
    }

}
