//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.07.25 at 12:15:02 AM CEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/policy/200803")
package org.oasis_open.docs.ns.bpel4people.ws_humantask.policy._200803;
