
package com.example.claims;

import javax.xml.ws.Endpoint;

/**
 * This class was generated by Apache CXF 2.4.2
 * 2011-09-24T22:28:50.411+02:00
 * Generated source version: 2.4.2
 * 
 */
 
public class ClaimsHandlingPT_ClaimHendlingPort_Server{

    protected ClaimsHandlingPT_ClaimHendlingPort_Server() throws java.lang.Exception {
        System.out.println("Starting Server");
        Object implementor = new ClaimsHandlingPTImpl();
        String address = "http://www.example.com/";
        Endpoint.publish(address, implementor);
    }
    
    public static void main(String args[]) throws java.lang.Exception { 
        new ClaimsHandlingPT_ClaimHendlingPort_Server();
        System.out.println("Server ready..."); 
        
        Thread.sleep(5 * 60 * 1000); 
        System.out.println("Server exiting");
        System.exit(0);
    }
}
